name: test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.24
      - name: Test
        run: |
          ./check.sh
      - name: Setup tmate session # see https://github.com/mxschmitt/action-tmate#only-on-failure
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}

